source "https://rubygems.org"

# Rails framework
gem "rails", "~> 7.2.3"

# Database
gem "pg", "~> 1.1"

# Web server
gem "puma", ">= 5.0"

# Windows tzinfo data
gem "tzinfo-data", platforms: %i[windows jruby]

# Boot optimization
gem "bootsnap", require: false

group :development, :test do
  # Debugging tools
  gem "debug", platforms: %i[mri windows], require: "debug/prelude"

  # Security static analysis
  gem "brakeman", require: false

  # Ruby style checks
  gem "rubocop-rails-omakase", require: false

  # Testing framework
  gem "rspec-rails", "~> 6.0"

  # FactoryBot for test data
  gem "factory_bot_rails"

  # Database cleaning
  gem "database_cleaner-active_record", "~> 2.2"
end
